### ISSUE TITLE
Unavailable GCP Automated BGP Session

### ISSUE THREAD

**Issue by zlion** [fabric-testbed/fabfed#113]
Ping can not get through for both native GCP and SENSE GCP cases.

```
- FAILED_TESTS:
  - failed_ssh_test: []
  - failed_ipv4_dataplane_ping_test:
    - src: sense-gcp-lzhang9-gcp-node-0
      destinations:
      - 192.168.10.3
    - src: fabric_node0
      destinations:
      - 10.200.1.2
      - 192.168.10.3
```

The reason is that the VLAN Attachment is not accepted on the Fabric side.

![Screen Shot 2024-03-08 at 8 52 28 PM](https://github.com/fabric-testbed/fabfed/assets/5992788/c77c57d0-ea25-4d87-a6da-01beb66ee34f)
