### ISSUE TITLE
Handle aws to gcp stitching via fabric

### ISSUE THREAD

**Issue by abessiari** [fabric-testbed/fabfed#143]
Note: Requires fablib extenstions 1.7.3

- using native providers
- stretch goal using sense

**Comment by abessiari** [comment]
Initial support has been checked in 
Requires fablib extenstions 1.7.3 
More testing in progress is needed to make sure other examples work.

**Comment by abessiari** [comment]
On fabric side a single l3vpn is created with both the gcp and aws facility ports.

```
'sliver': {'Labels': '{"local_name": "aes-native-aws-gcp-296256999979"}',
            'Layer': 'L3',
            'Name': 'aes-native-aws-gcp-fabric_network-0',
            'StitchNode': 'false',
            'Technology': 'AL2S',
            'Type': 'L3VPN',
            'interfaces': [{'Capacities': '{"bw": 50, "mtu": 1460}',
                            'Labels': '{"device_name": "agg4.ashb", '
                                      '"ipv4_subnet": "192.168.1.1/30", '
                                      '"local_name": "Bundle-Ether5"}',
                            'Name': 'Cloud-Facility-GCP-Cloud-Facility-GCP-int',
                            'NodeMap': '["Facility", "GCP,Cloud-Facility-GCP"]',
                            'PeerLabels': '{"account_id": '
                                          '"ee15249e-40c2-464a-9e1a-f0b64d798bd4/us-east4/any", '
                                          '"asn": "16550", "bgp_key": '
                                          '"0xzsEwC7xk6c1fK_h.xHyAdx", '
                                          '"ipv4_subnet": "192.168.1.2/30", '
                                          '"local_name": "Google Cloud '
                                          'Platform"}',
                            'StitchNode': 'false',
                            'Type': 'ServicePort'},
                           {'Capacities': '{"bw": 50, "mtu": 9001}',
                            'Labels': '{"device_name": "agg3.ashb", '
                                      '"ipv4_subnet": "192.168.1.1/30", '
                                      '"local_name": "TenGigE0/0/0/11/3"}',
                            'Name': 'Cloud-Facility-AWS-Cloud-Facility-AWS-int',
                            'NodeMap': '["Facility", "AWS,Cloud-Facility-AWS"]',
                            'PeerLabels': '{"account_id": "296256999979", '
                                          '"asn": "64512", "bgp_key": '
                                          '"0xzsEwC7xk6c1fK_h.xHyAdx", '
                                          '"ipv4_subnet": "192.168.1.2/30", '
                                          '"local_name": "AWS", "region": '
                                          '"us-east-1"}',
                            'StitchNode': 'false',
                            'Type': 'ServicePort'}]},
 'sliver_id': '2d8ba2e7-d115-4969-a19a-6524c64e75cb',
 'sliver_type': 'NetworkServiceSliver',

```

**Comment by abessiari** [comment]
The config file is under examples/demos

```
resource:
  - network:
      - gcp_net:
          provider: '{{ gcp.gcp_provider }}'
          name: gcp-net
          layer3: "{{ layer3.gcp_layer }}"
          peering: "{{ peering.gcp_peering }}"

      - fabric_network:
          provider: '{{ fabric.fabric_provider }}'
          peering: [ "{{ peering.gcp_peering }}", "{{ peering.aws_peering }}" ]
          count: 1
          stitch_with:
          - network: '{{ network.gcp_net }}'
            stitch_option:
                group_name: GCP
          - network: '{{ network.aws_net }}'
            stitch_option:
                device_name: agg3.ashb

      - aws_net:
          provider: '{{ aws.aws_provider }}'
          layer3: "{{ layer3.aws_layer }}"
          peering: "{{ peering.aws_peering }}"
                                              
```
