### ISSUE TITLE
Feature: CICD: Add support for github actions. 

### ISSUE THREAD

**Issue by abessiari** [fabric-testbed/fabfed#87]
- github action to deploy and destroy  chameleon network + 0 or more nodes + one fabric slice with stitch network + 0 or more fabric nodes. 
- github action to deploy and destroy  cloudlab network  + 0 or more nodes + 
one fabric slice with stitch network + 0 or more fabric nodes.

**Comment by abessiari** [comment]
@xi-yang 

- completed action to build docker image + run tests ...
- stuck with action to run stitching example with chameleon. 

Reason: my chameleon account got disabled. Likely reason multiple failed attempts to authenticate ... (Bad password)

Need help getting back my chameleon account. More on this in the meeting.

**Comment by abessiari** [comment]
These use cases are supported in cicd.

**L2STS**
```
resource:
  - node:
      - rocky_node:
            provider: '{{ fabric.fabric_provider }}'
            site: '{{ var.fabric_site }}'
      - other_node:
            provider: '{{ fabric.fabric_provider }}'
            site: '{{ var.other_fabric_site }}'
  - network:
      - fabric_network:
          provider: '{{ fabric.fabric_provider }}'
          layer3: "{{ layer3.my_layer }}"
          interface: [ '{{ node.rocky_node }}', '{{ node.other_node }}' ]
          count: 1
~                                       
```

**Comment by abessiari** [comment]
@xi-yang 

FABRIC TO SENSE. Can be run by setting an environment variable `RUN_FABRIC_AWS_SENSE` to true as it can take a long time. Good to run once in a while. 

```
resource:
  - node:
      - sense_node:
          provider: '{{ sense.sense_provider }}'
          network: "{{ network.sense_net }}"
          service:
      - fabric_node:
          provider: '{{ fabric.fabric_provider }}'
          site: MAX # Use RENC when deploying to fabric beta environment
          image: default_rocky_8
          nic_model: NIC_Basic
  - network:
      - sense_net:
          provider: '{{ sense.sense_provider }}'
          layer3: "{{ layer3.sense_layer }}"
          peering: "{{ peering.my_peering }}"
          stitch_with: '{{ network.fabric_network }}'
          stitch_option:
              device_name: agg3.ashb

      - fabric_network:
          provider: '{{ fabric.fabric_provider }}'
          layer3: "{{ layer3.fab_layer }}"
          peering: "{{ peering.my_peering }}"
          interface: '{{ node.fabric_node }}'
```

**Comment by abessiari** [comment]
Testing Fabric AWS. Fabric Only.  This way it runs faster.
This done by adding the stitch info and the peer layer3 to fabric network. 

resource:
  - node:
      - fabric_node:
          provider: '{{ fabric.fabric_provider }}'
          site: MAX

  - network:
      - fabric_network:
          provider: '{{ fabric.fabric_provider }}'
          layer3: "{{ layer3.fab_layer }}"
          peer_layer3: [ "{{ layer3.aws_layer }}" ]
          peering: "{{ peering.my_peering }}"
          interface: '{{ node.fabric_node }}'
          stitch_info:
            stitch_port:
              name: AWS_PORTS
              profile: FABRIC-AWS-DX-VGW
              provider: aws
              peer:
                profile: Cloud-Facility-AWS
                provider: fabric
                device_name: agg3.ashb
                local_name: TenGigE0/0/0/11/3
                site: AWS
            producer: fabric
            consumer: aws

**Comment by abessiari** [comment]
Cloudlab is also in there now.

Note the use of `network` instead of `interface` to express fabric node depending on fabric network. Like we doe for all other.
```
resource:
  - network:
      - cnet:
          provider: '{{cloudlab.cloudlab_provider }}'
          layer3: "{{ layer3.my_layer }}"
      - fabric_network:
          provider: '{{ fabric.fabric_provider }}'
          layer3: "{{ layer3.my_layer }}"
          # interface: '{{ node.fabric_node }}'
          stitch_with: '{{ network.cnet }}'
  - node:
      - fabric_node:
          provider: '{{ fabric.fabric_provider }}'
          site: '{{ var.site }}'
          network: "{{ network.fabric_network }}"
      - cnode:
          provider: '{{ cloudlab.cloudlab_provider }}'
          network: "{{ network.cnet }}"
```
